title: "mestr.io"
author: "mestr.io"
description: "Mester de Softwar√≠a" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

#url: https://mestr.io
#domain: mestr.io

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "info@mestr.io"
#twitter_username: "kroketen"
#github_username: "danibishop"
#linkedin_username: "danibishop"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  math_engine: katex
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      tags: Other
